### ISSUE TITLE
Storage with common header asking to create an rva account when I already have one

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#140]
See video overview here, http://www.screencast.com/t/yI2DDOf6J3F.

@tejohnso @fjvallarino This will need to be fixed before storage is deployed with common header. Shoot me an email and I can provide you the credentials for the user account this is occurring.

**Comment by fjvallarino** [comment]
@alanclayton Can we close this issue?

**Comment by alanclayton** [comment]
@fjvallarino Yes, you can close.
