### ISSUE TITLE
Loading message does not conform to style guide.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/storage-client#148]
http://www.screencast.com/t/ev1tvPCH9du2

Should be a loading spinner - http://rise-vision.github.io/style-guide/#/components/loading-spinner

**Comment by tejohnso** [comment]
@btfrise @ByronDarlison can this be closed or do we need to remove all loading  messages and use spinners instead?

**Comment by ByronDarlison** [comment]
@tejohnso first question. Why are you using something else other than the standard? Thanks

**Comment by tejohnso** [comment]
@ByronDarlison as per your message above from Nov26 I don't think there is a standard for when to include an informative message vs not to.  If there is a defined standard, I'd like to take a look at it.

**Comment by ByronDarlison** [comment]
@tejohnso the standard is a spinner. What I am asking is why do we need an informative message. What is it that we are informing the user about?

**Comment by tejohnso** [comment]
@ByronDarlison Any process that takes significant time.  Could be logging in, loading files, checking company authorization, deleting files, etc.  I think the conclusion is that we don't show those messages and instead show a spinner.  And if those states are taking very long to process, a message to the user isn't going to help.  The solution is to make it take less time.  Correct?

**Comment by ByronDarlison** [comment]
@tejohnso sorry. I am still lost here. When I start storage the only thing I see in terms of an informative message is "loading..." which from my perspective isn't information. It is the same thing as a spinner. If that is the case why would do something different? The standard is the spinner and the standard, unless changed everywhere else, is what we need to use.

And yes, everything needs to go faster so that whatever is shown is up for less time.

Thanks

**Comment by tejohnso** [comment]
@fjvallarino Let's go over these message bars one by one and start removing them.  One thing we want to make sure we avoid is having a spinner pop up and go away in rapid succession for multiple events.

**Comment by tejohnso** [comment]
@ByronDarlison and @fjvallarino As an example aside from the "loading..." message, the "Checking third party cookies" message should be removed.

**Comment by fjvallarino** [comment]
@btfrise This is fixed

**Comment by btfrise** [comment]
@fjvallarino confirmed, closing.
