### ISSUE TITLE
Can't download files from Storage after Subscription is Cancelled

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/storage-client#187]
If I try to download a file from Storage after I cancel my Storage subscription, I get a Login Required Message in the top left corner of the browser window and I can't do anything further on the page:

http://screencast.com/t/X2ZG0Pj7k1

You should be able to download your files from Storage if you are logged in, even if your subscription is cancelled.

**Comment by fjvallarino** [comment]
@AlexKolenoff Can we close this issue?

**Comment by AlexKolenoff** [comment]
@fjvallarino Yes, thanks.
