### ISSUE TITLE
Unable to upload files larger than 450 mb

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#188]
You are unable to upload files that are larger than 450mb. No error is provided. Just the message, "Upload did not complete"

A user should be able to upload a file that is at least 6 gb.

**Comment by tejohnso** [comment]
@alanclayton I think this can be closed now.  Please confirm.

**Comment by btfrise** [comment]
@tejohnso @alanclayton I've tested uploading 500m-6g files to storage with no errors. Everything looks great.

Closing.
