### ISSUE TITLE
Uploads fail >2GB.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/storage-client#195]
2+ GB file uploads fail on storage, screenshot attached.

http://www.screencast.com/t/YYMbMG2HXv

**Comment by tejohnso** [comment]
@btfrise I think this can be closed now. Please confirm.

**Comment by tejohnso** [comment]
@btfrise please confirm

**Comment by btfrise** [comment]
@tejohnso This is confirmed. Closing.
