### ISSUE TITLE
Filter placeholder text disappears and tag changes without applying changes on modal

### ISSUE THREAD

**Issue by ghislaineguerin** [Rise-Vision/storage-client#225]
@EnlightenedCode  Can’t clear tags on this modal too

**Comment by ghislaineguerin** [comment]
![vzx6yanead](https://cloud.githubusercontent.com/assets/845767/5750114/697d10e2-9c26-11e4-8086-aab6826e1779.gif)

**Comment by EnlightenedCode** [comment]
@ghislaineguerin yes there are a few issues when you branched off before yesterday.  me and francisco are still working to fix them

**Comment by EnlightenedCode** [comment]
@ghislaineguerin this is up for QA on http://rva-test.appspot.com/ can you confirm to me there in storage if you still see this bug? if not we can resolve this.

**Comment by fjvallarino** [comment]
@ghislaineguerin Is this issue still valid? Can we close it?

**Comment by ghislaineguerin** [comment]
We can close it.
