### ISSUE TITLE
User is able to enter tags with duplicate names

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#235]
The Tagging UI allows for tags to be created with duplicate names.  Duplicate names shouldn't be allowed.

**Comment by alanclayton** [comment]
A user can also enter duplicate Lookup values

**Comment by EnlightenedCode** [comment]
@alanclayton this should be resolved and the save button should now disable initially and only re-enable once a user puts a different name in order to save. it will not allow them to edit and save the same name. Thanks

**Comment by alanclayton** [comment]
@EnlightenedCode Verified. Thanks!

**Comment by alanclayton** [comment]
@EnlightenedCode Similar to having duplicate Lookup Values, we need to give a message to the User. The UI will let me enter a duplicate name and select save at which point I'm taken back to Tag Settings.

**Comment by EnlightenedCode** [comment]
@alanclayton this is now staged and needs to be confirmed. user will have a disabled save button with a name that is already in the type of tag they want to add (either lookup or freeform). it will display an error message saying "The Tag Definition name already exists". please confirm.

**Comment by alanclayton** [comment]
@EnlightenedCode verified.
