### ISSUE TITLE
Lookup Tags and Freeform Tags not using the correct table

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#236]
The tables for Lookup and Freeform tags are not using the responsive table defined in the style guide, http://rise-vision.github.io/style-guide/#/components/responsive-tables

**Comment by EnlightenedCode** [comment]
@alanclayton this will not be addressed until after this release is passed QA. there is another feature branch that address UI improvements like this.  this does not affect the release you are QAing right now

**Comment by fjvallarino** [comment]
@alanclayton Is this issue still valid?

**Comment by alanclayton** [comment]
@fjvallarino Yes, it is. The columns can't be sorted. Thanks

**Comment by mfisher11** [comment]
@alanclayton This is fixed and deployed. Closing issue.
