### ISSUE TITLE
User is able to enter Lookup values with duplicate names on the same tag

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#237]
Create a Lookup tag. Add two lookup values with the same name. The UI accepts both. 

Duplicate Lookup values shouldn't be allowed on the same tag.

**Comment by EnlightenedCode** [comment]
@alanclayton please confirm this is resolved on rva-test

**Comment by alanclayton** [comment]
@EnlightenedCode The workflow needs improvement. If I try to add a Lookup Value that is a duplicate of an existing, the UI let's me save the change and takes me back to the Tag Settings page. There was no explanation on what was wrong and we shouldn't allow the change to be saved. 

I think this can be addressed with the other UI improvements you are going to be working on.  I'll move to the Follow Up milestone.

@ghislaineguerin what should the workflow for this use case look like?

**Comment by EnlightenedCode** [comment]
@alanclayton good point.  We need to agree what we do on the client side should this happen. the server automatically just takes unique values and add its because it is a very rare event and probably done by user error. but I do think we should at least tell the user and not let him save.

**Comment by ByronDarlison** [comment]
@alan

**Comment by ByronDarlison** [comment]
@alanclayton I don't understand what the complexity is. Why do we need to figure this out? Shouldn't this just not allow duplicates and warn the user? Thanks

**Comment by EnlightenedCode** [comment]
@ByronDarlison @alanclayton I'll go ahead and make the button disable for duplicated values on the client. thanks

**Comment by tejohnso** [comment]
@EnlightenedCode If you do that you should also include a message letting the user know why the button is disabled.

**Comment by EnlightenedCode** [comment]
@tejohnso yes that is what I intend to do as well.

**Comment by alanclayton** [comment]
@ByronDarlison no complexity and we can fix now. @EnlightenedCode .before you do anything can you describe exactly how you propose we address this?

**Comment by ghislaineguerin** [comment]
@EnlightenedCode disable the button and show a message are ok with me.

**Comment by EnlightenedCode** [comment]
@alanclayton The save button will be disabled automatically when someone types a duplicated value in the comma seperated list.  and an alert error message will display above the buttons saying "Values for a Lookup Tag must all be unique." is that a good message?

**Comment by alanclayton** [comment]
@EnlightenedCode works for me. Thanks

**Comment by EnlightenedCode** [comment]
@alanclayton this is now fixed staged on rva-test. please confirm

**Comment by alanclayton** [comment]
@EnlightenedCode verified. Thanks
