### ISSUE TITLE
Changing the Name creates a new tag vs updating the existing

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#238]
1. Go to the Tag Settings page
2. Select an existing tag.
3. Change the name and save your change.
4. When you are taken back to the Tag Settings page you will see a new tag has been created that reflects your change vs updating the tag you changed. 

A new tag will be created if you modify the following of an existing tag,  Lookup Tag name, Lookup Tag value and Freeform Tag name

**Comment by alanclayton** [comment]
Additional info, simply selecting an existing tag and selecting save will also create a duplicate tag.

**Comment by EnlightenedCode** [comment]
@alanclayton This is how our update works and this is expected.  we need to delete and add.  renaming is the same as deleting.

**Comment by alanclayton** [comment]
@EnlightenedCode That doesn't make sense to me. Can you explain to me why this is expected?  Also, did you see the comment I added. If I just open a tag, then click save, a duplicate is created.

**Comment by EnlightenedCode** [comment]
@alanclayton that last one you mentioned is a bug. it should not let you save unless it shows there is a change in the name or values.  as far as the how the update works. I agree, it could be done a different way, but that is not how the storage-server was written so I had to follow the API which gave no means to update values by an ID, so I the client had to be made to delete and update causing the renaming of a name value to be the same as a delete. We can discuss this more with byron at our meeting.

**Comment by ByronDarlison** [comment]
What meeting? And seriously, that is a bug and it needs to be fixed, server
side and wherever else is required.

**Comment by EnlightenedCode** [comment]
@ByronDarlison it will be fixed. I'll discuss on hipchat how we go about that fix and get that feedback from you.

**Comment by EnlightenedCode** [comment]
@alanclayton please confirm this is resolved on rva-test

**Comment by alanclayton** [comment]
@EnlightenedCode This is fixed for the case of changing the name of an existing Lookup Tag name, but

1. I'm no longer able to create a Freeform Tag
2. A duplicate Lookup Tag is still created if I modify a Lookup Value of an existing Lookup Tag

**Comment by EnlightenedCode** [comment]
@alanclayton I will look into both of these thanks!

**Comment by EnlightenedCode** [comment]
@alanclayton please screen cast #2. #1 should work now.  I am unable to reproduce #2

**Comment by alanclayton** [comment]
@EnlightenedCode All issues verified. Thanks
