### ISSUE TITLE
There is no confirmation when deleting a tag

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#239]
If i delete a tag I should receive a confirmation modal with, "This Tag is about to be permanently deleted and it cannot be recovered" Style guide confirmation modal, http://rise-vision.github.io/style-guide/#/components/confirmation-modal

**Comment by EnlightenedCode** [comment]
@alanclayton please confirm this is resolved on rva-test

**Comment by EnlightenedCode** [comment]
@alanclayton this issue is no longer occuring confirmation is now given.
