### ISSUE TITLE
Start & End Dates don't save in Tagging Timeline

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#240]
1. Select an existing tag
2. Select in the "Add Timeline" field
3. uncheck "everyday" 
4. set a start date and end date to be whatever you want. Apply your changes
5. Close the tagging modal. Open the tag settings for the same file. 

There will be no start and end dates defined, but there should be based on performing the steps above.

**Comment by EnlightenedCode** [comment]
@alanclayton this issue is now resolved (due to error of configuration of rva-test). test and confirm on rva-test

**Comment by alanclayton** [comment]
@EnlightenedCode verified
