### ISSUE TITLE
Apply button on the Timeline modal not working as expected

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#241]
Once I've made all the changes to the Timeline I select Apply. Once I select Apply I would expect the modal to close, but it doesn't. i have to select the close button in the top right of the modal.

Once I select Apply, the modal should close.

**Comment by fjvallarino** [comment]
@alanclayton Is this issue still happening to you?

**Comment by alanclayton** [comment]
@fjvallarino no longer occurring.
