### ISSUE TITLE
UI lets you specify a Start Date that is after the End Date in Tagging Timeline

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#242]
1. Select an item in Storage with a tag
2. Select Timeline
3. Set Start Date to be Feb 3 2015
4. Set End Date to be Jan 31 2015

The UI should inform the User that this is invalid because the Start Date is after the End Date

**Comment by EnlightenedCode** [comment]
@alanclayton please confirm this is resolved in rva-test

**Comment by alanclayton** [comment]
@EnlightenedCode Looks good, but I can set my end date to be the same as the start date. What will happen in this scenario?

**Comment by EnlightenedCode** [comment]
@alanclayton good question.  I'll ask tyler and the others in hipchat what they think. I would think the displays will see that as start date beginning at 12:00am that day and end date ending 11:59pm that day if no time is entered.

**Comment by EnlightenedCode** [comment]
@alanclayton Tyler mentioned that it our presentation area does timeline this way that when you put the start date and end date...it saves 12:00am on both dates when you don't specify a start time and end time.  It also lets you do that. So we should follow that and let it be so here as well.  Anything else stopping this bug from being resolved?

**Comment by alanclayton** [comment]
@EnlightenedCode thanks. When you say "we should follow that" is there any work you need to do for Tagging to support that or is it already in place?

**Comment by EnlightenedCode** [comment]
@alanclayton its already in place.

**Comment by alanclayton** [comment]
@EnlightenedCode Thanks!
