### ISSUE TITLE
No tags are highlighted, when informing User of tags no longer available

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#243]
1. add a Lookup value to an item in storage.
2. From Tag settings, change the Lookup value assigned in step 1
3. Go back to the Tagging modal for the Storage item and select in the Lookup and change the Lookup value field.
4. The Tagging Lookup modal is opened and shows the message, "The highlighted Tags are no longer available and must be first deleted to proceed."

There is no tag highlighted as the message implies.

We need to highlight the tag in question so it is clear to the User which tag needs to be removed.

**Comment by tejohnso** [comment]
@fjvallarino can you check into this?

**Comment by mfisher11** [comment]
@alanclayton This issue has been resolved.
