### ISSUE TITLE
"Clear All" doesn't work on the modal from Filter by Lookup Tag

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#244]
1. From Storage select the Filter on the search bar
2. When the filter criteria expands select in the "filter by Lookup Tag" 
3. Enter any tag as your criteria and Apply
4. Select "Filter by Lookup Tag" again
5. The tag you selected from step 3 is shown. 
6. Select "Clear All

The tag is not removed. When I select "Clear All" any tags that were present as part of the search criteria should be removed and my search results should update to reflect that.

**Comment by EnlightenedCode** [comment]
@alanclayton this was confirmed to be working in our hangout discussion an hour ago right?

**Comment by alanclayton** [comment]
@EnlightenedCode You are correct. It is verified.
