### ISSUE TITLE
Tagged items that don't have a start/end date are not returned when searching by Timeline

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#246]
1. Tag an item  (don't specify a timeline)
2. Try to search for items by Timeline starting today.

The item that you set up in step 1 above is not returned in the results and should since it is implied that the file will play 24/7/365

**Comment by EnlightenedCode** [comment]
@alanclayton Are we sure this is how we want the filter to actually work? @ByronDarlison can you confirm that any file that does not have a timeline will still show up when you apply a filter? or should it automatically filter only files that have timelines on them?

**Comment by alanclayton** [comment]
@EnlightenedCode The use case for me is I want to see all items from Storage with the Lookup value "kansasbetterthantexas" that are scheduled to play from Jan 25 to Feb 3.

Storage items that have the Lookup value "kansasbetterthantexas" but no Timeline defined should fall into that criteria. Yes?

**Comment by EnlightenedCode** [comment]
@alanclayton I understand and I agree.  I'll go ahead and make the fix. thanks

**Comment by alanclayton** [comment]
Only returning files that have a timeline specified is by design. Closing issue.
