### ISSUE TITLE
Save & Cancel buttons don't appear on the new Tag page

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/storage-client#248]
Tested on Chrome iOS and Android.

Tag Settings -> New Tag page, no save or cancel buttons are available.

http://www.screencast.com/t/D2mzCwtksx

**Comment by EnlightenedCode** [comment]
@alanclayton  @btfrise this is resolved now and the fix is on rva-test. please confirm thanks

**Comment by btfrise** [comment]
Looks good. Thanks @EnlightenedCode
