### ISSUE TITLE
No confirmation modal when deleting tags.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/storage-client#251]
When deleting either Freeform or Lookup tags, no confirmation is presented for deletion.

Chrome Mobile (iOS and Android)

1. Create tag (Lookup or Freeform)
2. Delete tag, no confirmation modal is presented

**Comment by EnlightenedCode** [comment]
@btfrise @alanclayton is this in the Tag Settings page? Or are you talking about the "Clear All" button on the tagging modal ?

**Comment by btfrise** [comment]
@EnlightenedCode I have updated the bug post. This is from the tag settings page when deleting individual tags.

Screenshot - http://www.screencast.com/t/PAMhR5BSJ9kr

**Comment by EnlightenedCode** [comment]
@btfrise ok sorry, I think I copied code from when we didn't have the modal when I added the mobile buttons. I fixed it and it should be staged on rva-test. nice catch.

**Comment by btfrise** [comment]
Verified, thanks @EnlightenedCode
