### ISSUE TITLE
When uploading file to folder, file uploads to root directory.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/storage-client#252]
Steps to recreate:
1. Navigate to sub folder in storage
2. Select file to upload
3. Confirm file did not upload to sub folder
4. Navigate to root folder
5. Confirm file uploaded to root folder

Video overview - http://www.screencast.com/t/PsViys8l

How it should work:
1. Navigate to sub folder in storage
2. Select file to upload
3. Confirm file uploaded to sub folder

**Comment by fjvallarino** [comment]
@btfrise This is fixed at: http://storage.risevision.com/~rvi/storage-client-stage0/index.html

**Comment by btfrise** [comment]
Verified and closed.
