### ISSUE TITLE
Bottom half of the filename for the last item can't be seen when in a Sub Company

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#256]
1. From Storage, switch to the sub-company "Rise Display"
2. Scroll down until you reach the last item in the list
3. The bottom half of the filename is getting cut off.  http://www.screencast.com/t/lZF30jo3O

This does not happen if when you are in the Company you belong to. I assume this is caused by the notification bar informing the User they are in a sub Company. That bar adds 25px to the CH height. 

OS: MAC OS X 10.10.1
Chrome Version 40.0.2214.93 (64-bit)

@fjvallarino not a priority, but if you are working on other UI stuff and can fix at the same time that would be great.

**Comment by tejohnso** [comment]
@fjvallarino can you check into this?

**Comment by fjvallarino** [comment]
@alanclayton Is this issue still happening to you? I just uploaded several files to a subcompany and the scrollbar displays correctly.

**Comment by alanclayton** [comment]
@fjvallarino Issue is no longer occurring. Thanks
