### ISSUE TITLE
Files downloaded as folder-name-file-name.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/storage-client#258]
File names are currently being appended when downloaded.
Currently:
1. Select a file in storage
2. Click download from action bar
3. Navigate to downloaded file
4. File is downloaded as directory-name-file-name.extension
http://www.screencast.com/t/V5lzTobbt

How it should work:
1. Select a file in storage
2. Click download from action bar
3. Navigate to downloaded file
4. File is downloaded as file-name.extension

**Comment by alanclayton** [comment]
@tejohnso @fjvallarino I don't think this is a critical issue. Whoever takes this can you fit it into your schedule to fix over the next week? 

@btfrise can you update our QA test to include this use case. Thanks

**Comment by btfrise** [comment]
@alanclayton I've added the case.

**Comment by fjvallarino** [comment]
@btfrise This is deployed at: http://storage.risevision.com/~rvi/storage-client-stage0/index.html

**Comment by tejohnso** [comment]
@btfrise can this be closed?

**Comment by btfrise** [comment]
confirmed, closing.
