### ISSUE TITLE
Upload URI Request Failed

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/storage-client#261]
If a user is logged in and authenticated the API should receive their user name, and the error would be "Upload URI Request Failed for [email address]"

In some rare cases no user information is present.  In that situation the error message should suggest that the user log out and back in again.  I could not reproduce this scenario.

**Comment by ByronDarlison** [comment]
@tejohnso I am not so sure I follow the first part of this error description:

> If a user is logged in and authenticated the API should receive their user name, and the error would be "Upload URI Request Failed for [email address]"

When would this happen and what would cause it? And, is the error that the User would see "Upload URI Request Failed for [email address]"?

And is there a defect with this first part?

And with regards to the second part, is that what is being worked on to correct now? And what is the error that the user would see in this situation?

And how are these errors presented to the user? The error notification box or a modal?

Thanks

**Comment by tejohnso** [comment]
Error would be in the upload status box as is currently.  No change there.

The error that the user would see if not logged in is the same, minus their email address.  It should be changed to "It appears that you are not logged in.  Please log out and try logging in again." 

There is no defect on the first part. It indicates to the user that there is an error and shows them their email address just so they are aware of what account they're using.  This occurs in errors other than subscriptions status or failed user company validation.  A google side error, for example.

**Comment by ByronDarlison** [comment]
We talked. We need plain english error messages for both situations:

Something went wrong and we couldn't upload your file. Please try again.

We can't tell who you are. Can you please logout and log back in and try again.

Thanks

**Comment by tejohnso** [comment]
@fjvallarino Please change the english and spanish translations for upload-uri-request-failed and upload-uri-request-failed-email as per Byron's message above.  For the case where we have their email address just add it at the end in round brackets unless @ByronDarlison prefers something else.

**Comment by ByronDarlison** [comment]
@tejohnso why do they need to know what their email address is?

And see the last email that I just sent you with the subscription error message. That one needs plain English as well.

@fjvallarino can you give me a list of all error messages we show? Put them in a shared doc. Thanks

**Comment by tejohnso** [comment]
@ByronDarlison You're right.  For this case their email it isn't needed because we already confirmed their company status against their email address.  We used to handle all error scenarios in the same message and that's when we needed to include their email address.

**Comment by fjvallarino** [comment]
@tejohnso @ByronDarlison The email address was added per @alanclayton suggestion. It was because of an issue of logging in with two Google accounts on the same browser window, which sometimes resulted in the wrong account being used. Since there was no fix for that problem, the email was added as a way to notify the user that the wrong account was being used.

**Comment by tejohnso** [comment]
This was cleaned up with our error message overhaul.
