### ISSUE TITLE
Using the select all checkbox to select items returned from a search, then deleting, moves all items to trash

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#265]
Upload two files with the name "one.png" and "two.png". Once uploaded search for files with the name "one.png". You should see just a single file "one.png". Select the checkbox that you use to select all files. Then select Delete. 

All items in Storage are moved to the trash. My expectation was that I was just deleting the file "one.png". We should fix this so that either we only delete the file shown on screen or tell the User that everything is about to be deleted, not just the file "one.png"

**Comment by tejohnso** [comment]
@fjvallarino can you look into this?

**Comment by mfisher11** [comment]
@alanclayton This issue has been resolved.
