### ISSUE TITLE
CH disappears when a modal is opened over it on mobile

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/storage-client#270]
Referencing the screenshot here, http://www.screencast.com/t/hDcbaIhBn0c1

First, select on "Filters" from Storage. 

1.  Select "Add Lookup"
2.  Lookup Tag modal opens and shows over CH
3. Close the Lookup Tag modal and CH is gone. 

One way to correct is to refresh the page.

**Comment by alanclayton** [comment]
I can replicate CH disappearing when using the emulator tools in chrome dev tools. The difference is that in emulator I can swipe down to get CH back. On my mobile device, Samsung Galaxy S5, I can't do that.

Chrome ver 40.0.2214.90 is what I have on my Galaxy.

**Comment by alanclayton** [comment]
Okay, I'm bored. Here is a video of this happening http://www.screencast.com/t/GwcaZis8K. Captured this using the Live screencast feature outlined here, https://developer.chrome.com/devtools/docs/remote-debugging .

**Comment by EnlightenedCode** [comment]
@alanclayton this was an issue that was happening earlier in our use of modals with the CH.  @ghislaineguerin and me fixed a bug with all other modals...however I think this is a new modal I added later. so I need to apply the fix so that this bug doesn't appear.

**Comment by EnlightenedCode** [comment]
@alanclayton it is a one liner fix and I already got it reviewed and ready to merge.  here is the fix staged: http://storage.risevision.com/~rvi/storage-client-stage1/index.html#/ go ahead and confirm if the staging area fixes this.

**Comment by alanclayton** [comment]
Verified.  @EnlightenedCode do you have a card on the QA board for this one?

**Comment by EnlightenedCode** [comment]
@alanclayton I created one and its right here https://trello.com/c/vrd4dBX4/176-bugfix-ch-dissappears-in-mobile-on-filter-issue-270
