### ISSUE TITLE
scroll bar on mobile view does not work

### ISSUE THREAD

**Issue by EnlightenedCode** [Rise-Vision/storage-client#275]
@ghislaineguerin I on mobile view you get two scroll bars on a long file list so you won't be able to scroll correctly

**Comment by alanclayton** [comment]
@ghislaineguerin is this ready for QA?

**Comment by ghislaineguerin** [comment]
@alanclayton yes.

**Comment by alanclayton** [comment]
@ghislaineguerin I don't see a card on the QA board. Can you create one. Thanks

**Comment by EnlightenedCode** [comment]
@alanclayton alan this was only an additional update on common-style... and it was merged to master during the QAing of release #2 for tagging.  so you can confirm this on production if the bug is still there. It shouldn't be since the releases we did today should have picked up the latest common-style master version.

**Comment by alanclayton** [comment]
@mfisher11 can you verify this is fixed in production. Thanks

**Comment by mfisher11** [comment]
@alanclayton I think it's fixed.  I only see one scroll bar on the right, and scrolling seems to work in general.
