### ISSUE TITLE
Users with expired trials cannot download from storage.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/storage-client#276]
1. Switch to company with expired trial in storage
2. Select item from storage
3. Click download from action bar
4. Observe error message "Access DeniedAccess Denied"
5. No file is downloaded.

Users should be able to download their content from storage even if an account is canceled or a trial has expired.

**Comment by tejohnso** [comment]
This was happening in the case of some older files in a scenario that I hadn't thought of.  The problem has been corrected.

**Comment by alanclayton** [comment]
@btfrise can you verify.

**Comment by alanclayton** [comment]
@btfrise what is the status of this?

**Comment by btfrise** [comment]
@alanclayton Confirmed fixed. Closing.
