### ISSUE TITLE
In testing version: unable to get ellipsis-shortened tag names in modal

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/storage-client#277]
Expected results:  long tag names are supposed to be truncated and show an ellipsis.
(screenshot from trello)  http://goo.gl/Kdy9KY

Results I get:  long tag names extend beyond edges of modal.
http://goo.gl/SPWMrh
http://goo.gl/nvAewG  (developer console: sources -> sources)

Steps to reproduce:
1. New incognito window  (it is the first/only one, so no existing data is shared)
2. Open developer tools and under network, check disable cache
3. Go to http://storage.risevision.com/~rvi/storage-client-stage1/index.html#/
4. Sign in...
5. Click on tag icon to the right of (in this case) test119

This also occurs if the browser is emulating a mobile device (iphone 4):
http://goo.gl/akCho5

Or in a full android hardware emulator:
http://goo.gl/tbVYvd

**Comment by EnlightenedCode** [comment]
@mfisher11 this cannot be reproduced on my chrome emulator on my android note III on my personal phone. please hipchat me.

**Comment by alanclayton** [comment]
@mfisher11 Can you confirm the status of this one? Thanks

**Comment by mfisher11** [comment]
Issue has been resolved.
