### ISSUE TITLE
In testing version: warning/notice about deleted tag on a file

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/storage-client#278]
Expected results:  a notice about invalid tags.
http://goo.gl/JtDnML   (from trello)   or
http://goo.gl/pHM11C

Results I get:  no message about tags being invalid.
http://goo.gl/2YdSf0    (desktop, cache disabled)
http://goo.gl/kQRwgX  (emulated iphone4, cache disabled)
http://goo.gl/BPIhhi      (android hardware emulator)

Steps to reproduce:
1. New incognito window (it is the first/only one, so no existing data is shared)
2. Open developer tools and under network, check disable cache
3. Go to http://storage.risevision.com/~rvi/storage-client-stage1/index.html#/
4. Sign in...
5. Click on tag icon to the right of (in this case) smallfile    (levis tag does not actually exist now)

**Comment by EnlightenedCode** [comment]
@mfisher11 you only receive the message when you click edit on lookup tags... please confirm that you see the message on THIS edit screen and not the main screen. The main screen should not have any alert.

**Comment by EnlightenedCode** [comment]
![image](https://cloud.githubusercontent.com/assets/4974337/6066245/ee7c5c86-ad28-11e4-9b40-06b59ae4fef3.png)

**Comment by EnlightenedCode** [comment]
@mfisher11 go to that same screen and click edit (the pencil Icon).  that is where you should see the message. and the Clear All Invalid Tags link

**Comment by mfisher11** [comment]
Okay.  Looking in the wrong place, then.  Notice shows up as expected.
