### ISSUE TITLE
ce-storage.risevision.com "Create initial storage folder" button not appearing.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/storage-client#287]
Current problem:
1. Create new gmail account
2. Log in to ce-storage.risevision.com using new gmail account
3. Allow access from ce-storage.risevision.com to gmail account
4. Click upload button, upload a test item
5. Test item does not appear in storage, no Create initial storage folder prompt, no creation of trash folder.

Video of problem - http://www.screencast.com/t/7yDi4cfw

Should function:
1. Create new gmail account
2. Log in to ce-storage.risevision.com using new gmail account
3. Allow access from ce-storage.risevision.com to gmail account
4. Prompt for initial creation of storage folder
5. Click upload button, upload test item
6. Test item should appear in storage

**Comment by tejohnso** [comment]
"Create initial storage folder" button is no longer in use.  The initial folder should be created upon first file upload.

**Comment by btfrise** [comment]
@tejohnso Acknowledged. I'll open a new issue.
