### ISSUE TITLE
ce-storage.risevision.com Initial file upload does not create storage folders.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/storage-client#288]
Current problem:
1. Create new gmail account
2. Log in to ce-storage.risevision.com using new gmail account
3. Allow access from ce-storage.risevision.com to gmail account
4. Click upload button, upload a test item
5. Test item does not appear in storage, no trash folder is created, subscription trial becomes active.

Video of problem - http://www.screencast.com/t/3ln6VJrW3K0A

Should function:
1. Create new gmail account
2. Log in to ce-storage.risevision.com using new gmail account
3. Allow access from ce-storage.risevision.com to gmail account
4. Click upload button, upload test item
5. Test item should appear in storage, along with trash folder, subscription trial becomes active.

**Comment by tejohnso** [comment]
I think this may have been due to some backend  changes that went into production this morning.  

I've updated the ce-storage bulid to use the latest master client and couldn't duplicate the issue.
@btfrise Please check it out.
@alanclayton / @ByronDarlison FYI

**Comment by btfrise** [comment]
@tejohnso Looks good now. Thanks!
