### ISSUE TITLE
Removing iFrame prevents scrolling to see all content.

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/storage-client#301]
Steps to reproduce:
1. Go to http://storage-stage-0.risevision.com/
2. Try to scroll up or down with mouse wheel, arrow keys, or page up/down.

Result:
Unable to scroll (nothing happens).

How it should work:
It should scroll if there is more content than can fit on the screen.

Link to presentation:
N/A

OS
Xubuntu 14.04

Chrome Version:
Version 41.0.2272.76 (64-bit)

**Comment by tejohnso** [comment]
@fjvallarino In my browser I was able to fix this by adding overflow:auto to .storage-selector-iframe-full

**Comment by mfisher11** [comment]
Issue resolved.  Closing report.
