### ISSUE TITLE
Storage subscription status does not update when switching between companies

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/storage-client#305]
Steps to reproduce:
1. While logged into a company with either a Subscribed or Expired Storage subscription status, click on Storage and note the status.
2. From that same Storage page switch to a company that you know has a different Storage subscription status.  

Result:
The subscription status doesn't update when you switch to a company with a different subscription status.

How it should work:
The subscription status should change to reflect the correct status of the company's Storage you are looking at.

Example of what is currently happening: http://screencast.com/t/fzJ1ijf7an7U

OS:
Windows 7 64 bit
Chrome version 41.0.2272.89 m

**Comment by mfisher11** [comment]
@alanclayton @AlexKolenoff This is fixed and deployed.  Closing issue.
