### ISSUE TITLE
When clicking to Subscribe to Storage, the subscription box is very small

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/storage-client#306]
Steps to reproduce:
From a company that does not already have a Storage subscription, click to go to Storage, then click Subscribe

Result:
The page where you select your options to subscribe is a small box in the upper-left corner

How it should work:
The page with purchase options should be expanded so it does not need scroll bars to move around in

Example of what is currently happening:
http://screencast.com/t/xWcerZJarJ

OS:
Windows 7 64 bit
Chrome version 41.0.2272.89 m

**Comment by tejohnso** [comment]
@AlexKolenoff This has been corrected.  Please confirm.

**Comment by AlexKolenoff** [comment]
@tejohnso I am having difficulty confirming right now because any company that I switch to that don't have a subscription show they have a subscription.

**Comment by fjvallarino** [comment]
@AlexKolenoff The issue of subscription status not updating when switching to a sub company has been fixed. Could you check this one? Thank you!

**Comment by AlexKolenoff** [comment]
@fjvallarino Yep, it looks correct now, thanks!
@tejohnso The subscription box is fine as well.
