### ISSUE TITLE
Flash of unexpected title text on page load

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/storage-client#322]
1.  Access storage.risevision.com.
2.  Look at the tab title.
3.  Reload while looking at the tab title.  
4.  Notice it says "{{metatag.title}} before showing the expected page title.

@rodrigopavezi / @fjvallarino is this expected behaviour?  Why does something as simple as the document title need to be a programmed value?

**Comment by fjvallarino** [comment]
@tejohnso Based on a conversation I had with @rodrigopavezi, this is expected behaviour.

**Comment by tejohnso** [comment]
@rodrigopavezi can you clarify what is going on there?  Wondering why page title needs to be dynamic like that.

**Comment by fjvallarino** [comment]
@tejohnso This has been reverted. Can we close this issue? Thanks!
