### ISSUE TITLE
Common header appears in storage modal, makes modal unresponsive.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/storage-client#326]
Steps to reproduce:
1. Add a widget that uses storage selector to your presentation
2. Click the storage selector button
3. View storage modal

Result:
Notice that the storage modal is not responsive and only fills a small portion of the screen, the common header also appears - http://www.screencast.com/t/Y0TmwDEQ88r9

How it should work:
The modal should be fully responsive, there should be no common header in this modal - http://www.screencast.com/t/Iw4h8UNHWZi

OS:
OS X, Windows 7, Ubuntu 14.04

Chrome Ver:
41.0.2272.104

**Comment by ByronDarlison** [comment]
@tejohnso @fjvallarino can you let me know the plan for this defect? Thanks

**Comment by fjvallarino** [comment]
@ByronDarlison @tejohnso I don't actually think it's an issue on storage-client side. On http://rva.risevision.com, when creating a new presentation and selecting a file (image or video), the correct modal file selector is displayed. I don't know where to test this widget scenario, but I think probably the url they are using to display the modal selector is not correct (since modal does not include Common Header).

**Comment by ByronDarlison** [comment]
@fjvallarino okay. Do you think this defect should be moved to @alex-deaconu under RVA? Thanks

**Comment by fjvallarino** [comment]
@btfrise Is this issue happening on rva? I tested creating a presentation and adding a placeholder. From there, after choosing image/video I get the standard file selector without Common Header.

**Comment by alex-deaconu** [comment]
@fjvallarino @tejohnso if I understand correctly, you guys have changed the Storage Modal url that the RVA should use? Correct?

Thanks.

**Comment by fjvallarino** [comment]
@alex-deaconu No, we have not changed the URL.

**Comment by tejohnso** [comment]
@alex-deaconu you might be thinking of the staging and rva-test modal URLs.   Those were changed.

**Comment by alex-deaconu** [comment]
@tejohnso @fjvallarino got it. I can confirm, the RVA's storage selector is working as expected.

After taking a look at the RVA, I think this is an issue specific to the Storage selector used for Widgets (https://github.com/Rise-Vision/component-storage-selector).

@ByronDarlison FYI.

Thanks.

**Comment by ByronDarlison** [comment]
@alex-deaconu okay. Sounds like this is an issue for @donnapep / @stulees ? Let us know. Thanks

**Comment by btfrise** [comment]
@fjvallarino Yes, this is happened in rva.

**Comment by stulees** [comment]
@btfrise Are you experiencing this in rva-test or rva production? Also, did you only notice this with Video Widget (your screenshot) or other Widgets also? Thanks

**Comment by btfrise** [comment]
@stulees This is on production. I've just reviewed and it appears on all widgets that use the storage selector.

**Comment by stulees** [comment]
@fjvallarino @tejohnso Can you confirm this is the correct URL for production storage modal HTML - https://github.com/Rise-Vision/component-storage-selector/blob/master/src/config/prod.js#L3

**Comment by fjvallarino** [comment]
@stulees The correct url is http://storage.risevision.com/modal.html#/files/{companyId}

**Comment by stulees** [comment]
@btfrise @fjvallarino Thanks. The `companyId` already does get appended here - https://github.com/Rise-Vision/component-storage-selector/blob/master/src/dtv-storage-selector.js#L52

The production value of the modal URL used by storage selector component is correct. Functionality in this component has remained the same for a while. I'm not sure why common header would be appearing, the storage selector component does not have control over that. 

In regards to being fully responsive, the modal is being launched within the modal of the Widget settings, within RVA. It's likely there needs to be some CSS changes to apply the expected results as the storage selector does not have any influence on that either. I think common style (https://github.com/Rise-Vision/common-style) would be an appropriate place to log. @donnapep Agreed?

**Comment by fjvallarino** [comment]
@stulees Based on this https://github.com/Rise-Vision/component-storage-selector/blob/master/src/config/prod.js#L3, there is an extra "storage-" part in the name that should be removed.

**Comment by stulees** [comment]
@fjvallarino Ah, didn't catch that. Did this change when the URL for rva-test storage modal last changed? 

@btfrise Please log a bug to https://github.com/Rise-Vision/component-storage-selector for incorrect storage modal URL.

**Comment by fjvallarino** [comment]
@stulees No, the url for modal file selector has always been that one (modal.html). In fact, I'm surprised something is actually displayed, since storage-modal.html does not exist anymore (it was used internally by storage fullscreen).

**Comment by btfrise** [comment]
I have relogged this bug in the storage-selector repo. I am closing this issue. FYI @stulees
