### ISSUE TITLE
Applying a tag/timeline to a newly uploaded file fails unless content is reloaded first.

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/storage-client#339]
@btfrise This affects production as well as the staged version I was QA'ing.

Steps to reproduce:
1. Upload a file to storage.
2. Immediately after transfer is completed (don't navigate away/refresh/etc), apply a tag (lookup or freeform) or add a timeline.

Result:
You get the following error message:  "You don't have access to that action. Please contact your Administrator to give you the access you need." and the tag/timeline is not applied.

How it should work:
Tag should be applied, and modal disappears.

**NOTE
If, after uploading the file, the user hits F5 (to reload the screen), navigates to another folder and returns, removes a tag from another file, etc (pretty much anything that causes the content to be refreshed), applying a tag/timeline to that file works as expected.

Link to Presentation:
N/A

OS:
Xubuntu 14.04

Chrome Ver:
Version 41.0.2272.118 (64-bit)

**Comment by fjvallarino** [comment]
@mfisher11 This is fixed at: https://storage-stage-1.risevision.com

**Comment by mfisher11** [comment]
@fjvallarino This is confirmed fixed, however, the problem of not being able to create new folders exists here.

**Comment by fjvallarino** [comment]
@mfisher11 I will not deploy this fix until the other card is deployed. Then I will rebase.

**Comment by fjvallarino** [comment]
@mfisher11 Can we close this issue? Thanks!

**Comment by mfisher11** [comment]
Tag functionality has been removed.
