### ISSUE TITLE
Save button for tag setting not visible in narrow screen layout

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/storage-client#342]
I noticed this during e2e testing.

1.  Open http://storage.risevision.com in a decently sized window.
2.  Click Tag Settings
3.  Click Add Tag

Notice the Save / Cancel buttons are visible at the bottom right.

4.  Reduce the window width until they disappear.

Expectation:  They should no disappear.

@fjvallarino / @ghislaineguerin FYI

**Comment by fjvallarino** [comment]
@tejohnso Can we close this issue? Thanks!
