### ISSUE TITLE
Filter does not clear when clicking the adjacent "x" button

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/storage-client#359]
(observed in image folder widget, test version 0.1.1)

Steps to reproduce:
1. From the configuration modal in the image folder widget, click on the storage browse button (to the right of the URL)
2. Click on the find/magnifying glass.
3. Type the name of an existing folder (you will see the list reduce while typing)
4. Click on the smaller "x" to the right of the text entry field.

Result:
Text entry field disappears--but filter is still applied. The only folders showing in that list are those matching the filter. At this point, the only way to get the original list back is to re-open the filter field and manually erase the contents.

How it should work:
Clicking that "x" should erase the filter -or- erase the filter and close the text entry field.

Link to Presentation:
http://rva-test.appspot.com/#/PRESENTATION_MANAGE/id=d1139a47-3cea-4432-a78c-d966781ebd64?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443

OS:
Ubuntu 14.04

Chrome Ver:
Stable (42.0.2311)

**Comment by btfrise** [comment]
Confirmed fixed. FYI @fjvallarino
