### ISSUE TITLE
Clicking on the upload button in the storage modal does not open (local) file chooser window

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/storage-client#362]
** this was observed in the newly deployed version of the image widget **

Steps to reproduce:
1. Add image widget to a presentation.
2. Click on the link to configure the widget.
3. Click on the storage browser button (to right of URL text entry box)
4. Click on the button to upload a file.

Result:
Nothing happens.

How it should work:
Local file selector should appear to choose file to upload.

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=004c5a0d-0a46-444e-a2fa-4bdee09d0198?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

OS:
Xubuntu 14.04

Chrome Ver:
42.0.2311.152 (64-bit)

**Comment by fjvallarino** [comment]
@mfisher11 Can we close this issue? Thanks!

**Comment by mfisher11** [comment]
This issue has been resolved.
