### ISSUE TITLE
Storage modal contents change when browser switches to a different tab and then back

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/storage-client#363]
When in a sub-company with the storage modal open and showing files (for the current company), switching to a different tab and back again will cause the file list to refresh and show files in the user's (top level) company.

Steps to reproduce:
0. Open a presentation with a sub-company.
1. Add image widget to a presentation.
2. Click on the link to configure the widget.
3. Click on the storage browser button (to right of URL text entry box)
4. Make note of the files
5. Switch to a different tab.
6. Switch back to the tab with the storage modal.

Result:
Roughly a second later, the file list will refresh with content from the top-level/parent company.

How it should work:
If it refreshes at all, it should show the files from the current company.

Video (because this was hard to describe):
https://goo.gl/81VUnL

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=004c5a0d-0a46-444e-a2fa-4bdee09d0198?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

OS:
Xubuntu 14.04

Chrome Ver:
42.0.2311.152 (64-bit)

**Comment by fjvallarino** [comment]
@mfisher11 Can we close this issue? Thanks!

**Comment by mfisher11** [comment]
This issue has been resolved.
