### ISSUE TITLE
File Throttling tooltip does not appear in Storage App.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/storage-client#373]
Steps to reproduce:
1. Upload a file to storage
2. Trigger a throttle on that file by accessing it in a browser and refreshing the page

Result:
When the storage account is accessed through storage.risevision.com, a red exclamation point appears next to the throttled file. No tooltip is displayed.

When the storage account is accessed through the storage selector in a widget, a red exclamation point appears next to the throttled file, when clicked a tooltip is displayed.

How it should work:
A tooltip should be displayed when the exclamation point is clicked in the Storage App.

OS:
OS X 10.10

Chrome Ver:
43

**Comment by btfrise** [comment]
FYI @ByronDarlison 

Storage throttling has not been an issue lately, so this issue isn't a game breaker for us. Please consider that when assigning priority.

**Comment by ByronDarlison** [comment]
@btfrise thanks. @tejohnso @fjvallarino I would like to leave this one until after we ship the Offline Player to Customers. Do you guys concur? @btfrise if it becomes a common issue let us know and we will move it up. Thanks!

**Comment by tejohnso** [comment]
Okay by me

**Comment by ByronDarlison** [comment]
@ezequielc @alex-deaconu we should fix this as part of the storage work that is coming up. @RV-Adrian @ghislaineguerin anything to add from a UX perspective on this issue? Thanks

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;24wprpwp&#x2F;1125-https-github-com-rise-vision-storage-client-issues-373"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> https:&#x2F;&#x2F;github.com&#x2F;Rise-Vision&#x2F;storage-client&#x2F;issues&#x2F;373</a>
