### ISSUE TITLE
Uploading a file, if interrupted, can be stored in an incorrect location

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/storage-client#375]
Steps to reproduce:
1. Log into storage.
2. Create a sub-folder.
3. Enter that sub-folder.
4. Start uploading a file.
5. Simulate network interruption (unplug ethernet cable, turn off interface, etc)
6. Wait until the interruption is detected (retry button appears)
7. Reconnect
8. Tell it to retry/continue file upload.

Result:
Directory name will be duplicated (as another level in) and the file will be located there.  For example:
intended filename and location:     /bla/myfilename.mpg
resulting filename and location:     /bla/bla/myfilename.mpg

How it should work:
New sub-folder should not be created, and file should actually reside where it was intended.

Link to Presentation:
N/A

OS:
Xubuntu 15.04

Chrome Ver:
43.0.2357.132 (64-bit)

**Comment by ByronDarlison** [comment]
@mfisher11 thanks for finding this! @tejohnso @fjvallarino can you let us know your thoughts on this and if we can put it at the top of the queue. This is messing a user up badly. Thanks!

FYI @btfrise

**Comment by fjvallarino** [comment]
@mfisher11 A fix has been deployed to https://storage-stage-0.risevision.com

**Comment by mfisher11** [comment]
@fjvallarino Looks good, sir!  Testing on the stage location does not exhibit the problem.

**Comment by fjvallarino** [comment]
@mfisher11 Deployed.

@btfrise @ByronDarlison @tejohnso FYI

**Comment by mfisher11** [comment]
@fjvallarino Smoke test passed.  This now works in production.  Closing bug.

@btfrise @AlexKolenoff @justinsmith1 FYI

**Comment by ByronDarlison** [comment]
@fjvallarino thank you so much for taking care of this while on your holiday!
