### ISSUE TITLE
If opening the storage app from the storage modal, you will sometimes get a redirect_uri_mismatch

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/storage-client#377]
Steps to reproduce:
0. Ensure cache and any authentication tokens are cleared.
1. Open the storage modal from a widget.
2. At the top, click on "open in storage app".

Result:
You will be prompted to authenticate with google, then will get a redirect_uri_mismatch error

How it should work:
You may or may not be prompted to authenticate, but you should the storage app should open successfully and without an error.

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=737e57e5-410e-4be7-a02f-23b2c88a2821?cid=e514fd51-fadd-4e19-94af-f92549772c7f

OS:
Xubuntu 15.04

Chrome Ver:
43.0.2357.132 (64-bit)

I'm attaching a screenshot of the google error and providing a link to a video showing the problem.
(the video was part of a conversation, so that's why there's some unrelated details.)
https://drive.google.com/file/d/0B6-WaLVBL0sucE41cnB6VnFOREU/view?usp=sharing

![screenshot_2015-07-09_15-28-26](https://cloud.githubusercontent.com/assets/10407181/8629031/3adeb506-271d-11e5-859f-cf491f8e39e9.png)

**Comment by ByronDarlison** [comment]
@mfisher11 @RV-Adrian @ghislaineguerin @alex-deaconu @ezequielc @fjvallarino does anyone know if this defect is still open? Thanks

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;axfN6cvZ&#x2F;1124-https-github-com-rise-vision-storage-client-issues-377"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> https:&#x2F;&#x2F;github.com&#x2F;Rise-Vision&#x2F;storage-client&#x2F;issues&#x2F;377</a>

**Comment by mfisher11** [comment]
@ByronDarlison I don't think this is an issue any more as the "open in storage app" button is no longer present.  I tried to replicate with the image widget and video widget.

**Comment by ByronDarlison** [comment]
Okay. Thanks @mfisher11
