### ISSUE TITLE
Start trial button getting cut off in Storage Selector modal

### ISSUE THREAD

**Issue by brianloosbrock** [Rise-Vision/storage-client#380]
**How it works now**
Start trial button is below the modal break .
![image](https://cloud.githubusercontent.com/assets/6887543/8831246/c1922b44-3066-11e5-9906-c440915d450b.png)

**How it should work**
The entire message should be visible above the modal window so Users can start a trial. @RV-Adrian It looks to be approx 400 pixels of high that we need to stay within. Can you tweak the message and graphic so it fits comfortably within 400 pixels and provide to @fjvallarino to update the selector. @fjvallarino once you have it staged please let us know and we can do a quick review. Thanks

**Comment by RV-Adrian** [comment]
@brianloosbrock @fjvallarino Yep, I can adjust for that now. Another option would be increasing the height of the modal itself from 500px to 680px as seen here: http://goo.gl/h8HQPq 

![image](https://cloud.githubusercontent.com/assets/11826611/8831706/1fe5c222-3072-11e5-9fbd-fa82f1f800fb.png)

Any thoughts?

**Comment by brianloosbrock** [comment]
@fjvallarino I'll defer to you on what you want to do, just let us know as I'd like to resolve this today. Thanks

**Comment by brianloosbrock** [comment]
@fjvallarino Lets deploy this fix when your ready. Thanks

**Comment by brianloosbrock** [comment]
Fix confirmed. Closing.
