### ISSUE TITLE
When trying to specify which image should be used as an image item, not all of the images in storage are visible to choose from

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/storage-client#389]
**THIS REFERENCES A LIVE PRESENTATION AND COMPANY STORAGE. DO NOT MODIFY

Steps to reproduce:
1) Open this presentation: http://rva.risevision.com/#/PRESENTATION_MANAGE/id=99d4d96d-5585-4a8e-a9f9-e963cdacf1fb?cid=fa5ffa88-c4d4-478d-bd41-b31b9ae037fc
2) In "sponsors" placeholder (right side) click to add an image item
3) Click on the storage link to the right of URL
4) Approx 18 files are listed with no indication that there are more available.
5) Click on "Open in storage app"
6) I had to copy and replace the company id for it to show the correct contents:
https://storage.risevision.com/files/fa5ffa88-c4d4-478d-bd41-b31b9ae037fc?cid=fa5ffa88-c4d4-478d-bd41-b31b9ae037fc

Result:
Observe that there are MANY more than the listed 18 files in the initial selector.

How it should work:
All image files listed after step 6 should be visible in step 4. 

OS:
Xubuntu 15.10, WIn7 and Win8

Chrome Ver:
45.0.2454.101-1

**Comment by fjvallarino** [comment]
@mfisher11 This is fixed on production now

**Comment by mfisher11** [comment]
Confirmed and closing.  Thanks @fjvallarino
