### ISSUE TITLE
Uploading a folder or multiple files as a user's first upload generates an error

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/storage-client#399]
From the logs at storage.rvaserver2.appspot.com:
http://screencast.com/t/zouApK51Z

When uploading a folder, multiple upload URL requests are generated. As seen in the logs, the first request succeeds, however subsequent requests result in:
503: Backend Error
500: Backend Error
409: You already own this bucket. Please select another name.

Also, for some reason the server gets stuck on creating bucket for quite some time so uploads won't work (bucket creation attempts shouldn't occur afterwards). Once the server ceases to attempt to create the bucket, everything works as expected.

Thanks.

**Comment by alex-deaconu** [comment]
@rjcahoy just an FYI. This is the Storage Issue with uploading to new accounts you reported a couple of days ago in Hipchat. It should be fixed as of now. 

I've verified it, however if you want to give it a quick spin to ensure everything works correctly, you're more than welcome to.

Thanks!

**Comment by lapinnoir** [comment]
@alex-deaconu I have tested this out and can confirm that I am able to do multiple uploads on new subscriptions.
While testing this out, I came across another bug around the Remove link.  See https://github.com/Rise-Vision/storage-client/issues/401
