### ISSUE TITLE
Remove link does not work when uploading multiple files in Storage

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/storage-client#401]
**Problem to be Solved**
When I start my Storage subscription or enter my Storage and I upload multiple files at the same time, I am not able to Remove the list of file/s that I want to delete.  I can only select the 'Remove' link on the file while it is being uploaded.

In this recording, I am selecting the 'Remove' link on two image links but was not able to remove them.  However I was able to select the Remove link on the file that is currently being uploaded http://g.recordit.co/XlBVZiqmJg.gif

**What I expect to happen**
When I upload multiple files into Storage, I am able to use the Remove link to decide which files I no longer want uploaded.

Chrome ver 47.0.2526.106

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;2b0sy9Hp&#x2F;1123-https-github-com-rise-vision-storage-client-issues-401"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> https:&#x2F;&#x2F;github.com&#x2F;Rise-Vision&#x2F;storage-client&#x2F;issues&#x2F;401</a>

**Comment by ezequielc** [comment]
@hcs0 This is fixed for the new Storage file selector in Apps. We are going to replace Storage and reuse this code, so if you confirm it works in the new file selector, we can close this issue. Thanks

**Comment by hcs0** [comment]
@ezequielc I cleared cache and tried with both storage.risevision.com and https://storage-stage-0.risevision.com/ - can only Remove files if the upload progress bar is on it still http://g.recordit.co/TSoOHjmTvv.gif

**Comment by ezequielc** [comment]
@hcs0 The issue was fixed only in apps.risevision.com Storage file selector (by changing Presentation background or Placeholder background). Both links you mentioned are not going be fixed as they are going to be replaced soon. Thanks!

**Comment by hcs0** [comment]
@ezequielc Thanks, it works!

**Comment by ezequielc** [comment]
Thanks @hcs0
