### ISSUE TITLE
Empty State remains when file is being uploaded

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/storage-client#402]
![bugg4](https://cloud.githubusercontent.com/assets/11826611/12300795/0abb3028-b9eb-11e5-9abb-aa518be74142.gif)

**Comment by RV-Adrian** [comment]
@alex-deaconu Tried again with non-staged environment. Screencap above.  Thx!

**Comment by ByronDarlison** [comment]
@RV-Adrian can you confirm what should be happening instead with this issue and if there is any UX work involved? Thanks

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;4TwCIco8&#x2F;1122-https-github-com-rise-vision-storage-client-issues-402"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> https:&#x2F;&#x2F;github.com&#x2F;Rise-Vision&#x2F;storage-client&#x2F;issues&#x2F;402</a>

**Comment by ezequielc** [comment]
@RV-Adrian This issue was fixed, you can validate it in https://apps.risevision.com/storage-selector.html#/. Thanks

**Comment by ezequielc** [comment]
Validated in the card. I am closing the issue. Cheers
