### ISSUE TITLE
Duplicate 'Cookie Blocked' message in Storage client

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/storage-client#403]
![cookie](https://cloud.githubusercontent.com/assets/11826611/12330819/f05ca8d6-bab4-11e5-92fe-169733fcd1fa.jpg)

Cookie error messages need to be removed from storage-client, and remain in Common Header.
For now, I will add `ng-hide` until @ezequielc can clear the Angular code involved. Thx!

**Comment by ByronDarlison** [comment]
@RV-Adrian can you confirm if this issue is still open?

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hkt0FRk1&#x2F;1121-https-github-com-rise-vision-storage-client-issues-403"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> https:&#x2F;&#x2F;github.com&#x2F;Rise-Vision&#x2F;storage-client&#x2F;issues&#x2F;403</a>

**Comment by alex-deaconu** [comment]
@ByronDarlison @ezequielc since we've moved Storage to Apps, this issue no longer applies. Closing. Thanks.
