### ISSUE TITLE
View invoices from subscription status opens Store in a unreadable iframe window

### ISSUE THREAD

**Issue by brianloosbrock** [Rise-Vision/storage-client#406]
Over of the issue here https://goo.gl/w13NQA. 

@ByronDarlison @ezequielc I think this is something we should fix right away so people who are trying to reactive their account can. Thanks

**Comment by ByronDarlison** [comment]
Agreed @brianloosbrock. @alex-deaconu @ezequielc what do you guys think? And if you concur? Can we add this to the next sprint backlog? Thanks!

**Comment by alex-deaconu** [comment]
@brianloosbrock this issue is fixed in production. Please verify. 

@ByronDarlison @ezequielc FYI. Thanks.

**Comment by brianloosbrock** [comment]
@alex-deaconu Verified. Closing. Thanks
