### ISSUE TITLE
Not able to download a group of selected files

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/storage-client#412]
**How to recreate**
1. Go to storage-stage-0.risevision.com
2. Download a group of files
3. Select a group of files and select the Download button

**What happens**
The download does not start for these groups of files

 http://recordit.co/UfbEySabVj

**What should happen**
The download should start for these group of files

**Notes**
Chr 49.0.2623.87
Does not happen in storage.risevision.com

**Comment by hcs0** [comment]
Does not occur in storage.risevision.com

**Comment by ezequielc** [comment]
@alex-deaconu @ByronDarlison @hcs0 As it only occurs in stage, are we ok to close this issue?

**Comment by alex-deaconu** [comment]
@ezequielc agreed. Thanks.
