### ISSUE TITLE
storage-client.No user error when moving a selected group of files to Trash

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/storage-client#414]
**How to recreate**
1. Create a new user and add to the Test Company
2. Enable Storage for the user on storage-stage-0.risevision.com
3. Upload multiple files
4. Select a group of files to be added to Trash

**What happens**
Was not able to select the group of files to go to Trash.

<img width="565" alt="screen shot 2016-03-25 at 1 57 11 pm" src="https://cloud.githubusercontent.com/assets/5868781/14050327/7db34e24-f291-11e5-8204-4697d12814a4.png">

The storage-stage-0.risevision.com suddenly reloaded and I had to sign in again.

After signing in again, move to trash succeeded on second try http://g.recordit.co/fjAAqDMENi.gif

**What should happen**
User should be able to select files and move to Trash on the first try.

**Notes**
Chr 49.0.2623.87
May have been an intermittent error
Does not happen in storage.risevision.com

**Comment by hcs0** [comment]
Does not occur in storage.risevision.com

**Comment by ezequielc** [comment]
@alex-deaconu @ByronDarlison @hcs0 As it only occurs in stage, are we ok to close this issue?

**Comment by alex-deaconu** [comment]
@ezequielc agreed. Thanks.
