### ISSUE TITLE
Pop up appears in Chrome asking user permission to download multiple files

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/storage-client#415]
**How to recreate**
1. Log in as an existing user in the Test company
2. Go to a folder hosted on storage-stage-0.risevision.com (in this case it was Image Folder Issue 20 / Images folder)
3. Select the all button
4. Select the Download button

**What happens**
A pop up window appears in Chrome asking the user permission to download multiple files

![screen shot 2016-03-25 at 1 45 06 pm](https://cloud.githubusercontent.com/assets/5868781/14050432/3e20533c-f292-11e5-9486-1a5ab4c9ea2a.png)

I have not selected Block or Allow but was able to download one file (called Images-Image Folder Issue 20-Fall Semester 2015 002 (1).jpeg)

After exiting the folder and going back to the same folder again, I was not able to download multiple files again: http://g.recordit.co/yUMo7oac0R.gif

**What should happen**
User should be able to select files and download all files without seeing the pop up.
User should be able to download the selected files (see related issue at https://github.com/Rise-Vision/storage-client/issues/412)

**Notes**
Chr 49.0.2623.87
Does not occur in storage.risevision.com

**Comment by hcs0** [comment]
Does not occur in storage.risevision.com

**Comment by ezequielc** [comment]
@alex-deaconu @ByronDarlison @hcs0 As it only occurs in stage, are we ok to close this issue?

**Comment by alex-deaconu** [comment]
@ezequielc agreed. Thanks.
