### ISSUE TITLE
Error: origin_mismatch while trying to access Google Account.

### ISSUE THREAD

**Issue by techchad** [Rise-Vision/storage-client#87]
I just installed and setup the storage client it's on a Windows 2008 R2 box.  When I access the storage-modal.html a banner comes across that states Rise Vision needs access to your Google account to verify who you are.  When i click ok I get the attached error.  I am using two-factor authentication with my google account.  I did clear my cache and cookies and it had me re-authorize the account and it gave me the same error message after I put in the password and pass code for two-factor authentication.

![rise-error](https://cloud.githubusercontent.com/assets/318244/4307122/ad1d035a-3e86-11e4-97c5-806938cc0a4d.jpg)

**Comment by tejohnso** [comment]
Should work on localhost as described in README.md.  Closing.
